### ISSUE TITLE
Tensors on CPU and GPU

### ISSUE THREAD

**Issue by alhojel** [roeehendel/icl_task_vectors#4]
`[nltk_data] Downloading package wordnet to /home/ahojel/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /home/ahojel/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
Evaluating model: llama 7B
Loading model and tokenizer...

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
Loading checkpoint shards:  50%|█████     | 1/2 [00:02<00:02,  2.85s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:03<00:00,  1.77s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:03<00:00,  1.93s/it]
Loaded model and tokenizer.
WARNING: mapping present_simple_past_perfect has only 69 examples after filtering (110 before)
WARNING: mapping singular_plural has only 31 examples after filtering (173 before)
WARNING: mapping plural_singular has only 44 examples after filtering (172 before)

==================================================
Running task 1/27: translation_fr_en
/home/ahojel/.local/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:392: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/ahojel/.local/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:397: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
/home/ahojel/.local/lib/python3.10/site-packages/transformers/generation/utils.py:1413: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on cpu, whereas the model is on cuda. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('cuda') before running `.generate()`.
  warnings.warn(
Traceback (most recent call last):
  File "/home/ahojel/icl_task_vectors/shared/miniconda3/envs/icl_task_vectors/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ahojel/icl_task_vectors/shared/miniconda3/envs/icl_task_vectors/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ahojel/icl_task_vectors/scripts/experiments/main.py", line 159, in <module>
    main()
  File "/home/ahojel/icl_task_vectors/scripts/experiments/main.py", line 147, in main
    run_main_experiment(model_type, model_variant, experiment_id=experiment_id)
  File "/home/ahojel/icl_task_vectors/scripts/experiments/main.py", line 111, in run_main_experiment
    accuracies, tv_ordered_tokens_by_layer = evaluate_task(model, tokenizer, task_name, num_examples)
  File "/home/ahojel/icl_task_vectors/scripts/experiments/main.py", line 48, in evaluate_task
    tv_predictions, tv_dev_accuracy_by_layer, task_hiddens = run_task_vector(
  File "/home/ahojel/icl_task_vectors/core/task_vectors.py", line 48, in run_task_vector
    dev_accuracy_by_layer = task_vector_accuracy_by_layer(
  File "/home/ahojel/icl_task_vectors/core/task_vectors.py", line 265, in task_vector_accuracy_by_layer
    answers = modulated_generate(
  File "/home/ahojel/icl_task_vectors/core/task_vectors.py", line 188, in modulated_generate
    first_forward_outputs = modulated_forward(
  File "/home/ahojel/icl_task_vectors/core/task_vectors.py", line 229, in modulated_forward
    first_forward_outputs = modified_forward(
  File "/home/ahojel/icl_task_vectors/core/models/utils/inference.py", line 49, in modified_forward
    outputs = batch_forward(
  File "/home/ahojel/icl_task_vectors/core/models/utils/inference.py", line 110, in batch_forward
    out = model(**batch_inputs, **forward_kwargs)
  File "/home/ahojel/icl_task_vectors/shared/miniconda3/envs/icl_task_vectors/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ahojel/icl_task_vectors/shared/miniconda3/envs/icl_task_vectors/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ahojel/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/ahojel/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1183, in forward
    outputs = self.model(
  File "/home/ahojel/icl_task_vectors/shared/miniconda3/envs/icl_task_vectors/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ahojel/icl_task_vectors/shared/miniconda3/envs/icl_task_vectors/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ahojel/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1070, in forward
    layer_outputs = decoder_layer(
  File "/home/ahojel/icl_task_vectors/shared/miniconda3/envs/icl_task_vectors/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ahojel/icl_task_vectors/shared/miniconda3/envs/icl_task_vectors/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1561, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/ahojel/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/ahojel/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 798, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/ahojel/icl_task_vectors/shared/miniconda3/envs/icl_task_vectors/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ahojel/icl_task_vectors/shared/miniconda3/envs/icl_task_vectors/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ahojel/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/ahojel/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 710, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/home/ahojel/.local/lib/python3.10/site-packages/transformers/cache_utils.py", line 127, in update
    self.key_cache[layer_idx] = torch.cat([self.key_cache[layer_idx], key_states], dim=-2)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:1! (when checking argument for argument tensors in method wrapper_CUDA_cat)
`

It appears I may have a problem with the cache utils for the transformer lib and the fact that it is on the CPU. Any idea where I could start to debug this?

**Comment by DerrickRose2019** [comment]
I had the same problem as you. Have you fixed it yet？？

**Comment by DerrickRose2019** [comment]
> `[nltk_data] Downloading package wordnet to /home/ahojel/nltk_data... [nltk_data] Package wordnet is already up-to-date! [nltk_data] Downloading package omw-1.4 to /home/ahojel/nltk_data... [nltk_data] Package omw-1.4 is already up-to-date! Evaluating model: llama 7B Loading model and tokenizer...
> 
> Loading checkpoint shards: 0%| | 0/2 [00:00<?, ?it/s] Loading checkpoint shards: 50%|█████ | 1/2 [00:02<00:02, 2.85s/it] Loading checkpoint shards: 100%|██████████| 2/2 [00:03<00:00, 1.77s/it] Loading checkpoint shards: 100%|██████████| 2/2 [00:03<00:00, 1.93s/it] Loaded model and tokenizer. WARNING: mapping present_simple_past_perfect has only 69 examples after filtering (110 before) WARNING: mapping singular_plural has only 31 examples after filtering (173 before) WARNING: mapping plural_singular has only 44 examples after filtering (172 before)
> 
> ================================================== Running task 1/27: translation_fr_en /home/ahojel/.local/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:392: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. warnings.warn( /home/ahojel/.local/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:397: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. warnings.warn( /home/ahojel/.local/lib/python3.10/site-packages/transformers/generation/utils.py:1413: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on cpu, whereas the model is on cuda. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('cuda') before running `.generate()`. warnings.warn( Traceback (most recent call last): File "/home/ahojel/icl_task_vectors/shared/miniconda3/envs/icl_task_vectors/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/home/ahojel/icl_task_vectors/shared/miniconda3/envs/icl_task_vectors/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/home/ahojel/icl_task_vectors/scripts/experiments/main.py", line 159, in main() File "/home/ahojel/icl_task_vectors/scripts/experiments/main.py", line 147, in main run_main_experiment(model_type, model_variant, experiment_id=experiment_id) File "/home/ahojel/icl_task_vectors/scripts/experiments/main.py", line 111, in run_main_experiment accuracies, tv_ordered_tokens_by_layer = evaluate_task(model, tokenizer, task_name, num_examples) File "/home/ahojel/icl_task_vectors/scripts/experiments/main.py", line 48, in evaluate_task tv_predictions, tv_dev_accuracy_by_layer, task_hiddens = run_task_vector( File "/home/ahojel/icl_task_vectors/core/task_vectors.py", line 48, in run_task_vector dev_accuracy_by_layer = task_vector_accuracy_by_layer( File "/home/ahojel/icl_task_vectors/core/task_vectors.py", line 265, in task_vector_accuracy_by_layer answers = modulated_generate( File "/home/ahojel/icl_task_vectors/core/task_vectors.py", line 188, in modulated_generate first_forward_outputs = modulated_forward( File "/home/ahojel/icl_task_vectors/core/task_vectors.py", line 229, in modulated_forward first_forward_outputs = modified_forward( File "/home/ahojel/icl_task_vectors/core/models/utils/inference.py", line 49, in modified_forward outputs = batch_forward( File "/home/ahojel/icl_task_vectors/core/models/utils/inference.py", line 110, in batch_forward out = model(**batch_inputs, **forward_kwargs) File "/home/ahojel/icl_task_vectors/shared/miniconda3/envs/icl_task_vectors/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/ahojel/icl_task_vectors/shared/miniconda3/envs/icl_task_vectors/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl return forward_call(*args, **kwargs) File "/home/ahojel/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward output = module._old_forward(*args, **kwargs) File "/home/ahojel/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1183, in forward outputs = self.model( File "/home/ahojel/icl_task_vectors/shared/miniconda3/envs/icl_task_vectors/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/ahojel/icl_task_vectors/shared/miniconda3/envs/icl_task_vectors/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl return forward_call(*args, **kwargs) File "/home/ahojel/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1070, in forward layer_outputs = decoder_layer( File "/home/ahojel/icl_task_vectors/shared/miniconda3/envs/icl_task_vectors/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/ahojel/icl_task_vectors/shared/miniconda3/envs/icl_task_vectors/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1561, in _call_impl result = forward_call(*args, **kwargs) File "/home/ahojel/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward output = module._old_forward(*args, **kwargs) File "/home/ahojel/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 798, in forward hidden_states, self_attn_weights, present_key_value = self.self_attn( File "/home/ahojel/icl_task_vectors/shared/miniconda3/envs/icl_task_vectors/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/ahojel/icl_task_vectors/shared/miniconda3/envs/icl_task_vectors/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl return forward_call(*args, **kwargs) File "/home/ahojel/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward output = module._old_forward(*args, **kwargs) File "/home/ahojel/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 710, in forward key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs) File "/home/ahojel/.local/lib/python3.10/site-packages/transformers/cache_utils.py", line 127, in update self.key_cache[layer_idx] = torch.cat([self.key_cache[layer_idx], key_states], dim=-2) RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:1! (when checking argument for argument tensors in method wrapper_CUDA_cat) `
> 
> It appears I may have a problem with the cache utils for the transformer lib and the fact that it is on the CPU. Any idea where I could start to debug this?

I had the same problem as you. Have you fixed it yet

**Comment by alhojel** [comment]
I was indeed able to fix it. I believe you just have to verify that all the tensors are moved to the same GPU. I suggest going through the debugger printing the device of each tensor.

**Comment by DerrickRose2019** [comment]
Thanks , it is helpful!
